/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Options {
  gzip: boolean
  brotli: boolean
  fileExtensions: Array<string>
  batchSize: number
}
export declare function runSqueezer(options: Options, dir: string): Promise<void>
